services:
  app:
    image: ghcr.io/gendosu/claude-code-docker:latest
    container_name: claude-code-container
    environment:
      NODE_ENV: production
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_ID: ${GITHUB_ID}
    volumes:
      - ${PWD}:${PWD}
    working_dir: ${PWD}
    stdin_open: true  # equivalent to -i
    tty: true         # equivalent to -t
