name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '00 21 * * *'  # 日本時間06:00に対応するUTC時間は前日の21:00

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get claude-code version
        id: get_version
        run: |
          # Extract claude-code version from package.json
          VERSION=$(cat package.json | jq -r '.dependencies."@anthropic-ai/claude-code"' | sed 's/[^0-9.]//g')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Claude-code version: $VERSION"

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest
            ghcr.io/${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}
            ${{ secrets.DOCKERHUB_USERNAME }}/claude-code-docker:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/claude-code-docker:${{ steps.get_version.outputs.VERSION }}
          platforms: linux/amd64,linux/arm64
